name: dashcast
description: A podcast player written in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sound: ^1.5.2
  webfeed: ^0.4.2
  http: ^0.12.0+2
  provider: ^3.1.0
  path_provider: ^1.4.0
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/surf_shimmy.mp3